AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Serverless Specification template describing your function.
Resources:
  sendToLINEWORKS:
    Type: 'AWS::Serverless::Function'
    Properties:
      FunctionName: sendToLINEWORKS
      Description: ''
      Handler: index.handler
      MemorySize: 128
      Role: >-
        arn:aws:iam::{AccountID}:role/service-role/sendToLINEWORKS-role-bsqjxsum
      Runtime: nodejs12.x
      Timeout: 3
