AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Serverless Specification template describing your function.
Resources:
  recieveFromSlack:
    Type: 'AWS::Serverless::Function'
    Properties:
      FunctionName: recieveFromSlack
      Description: ''
      Handler: index.handler
      MemorySize: 128
      Role: >-
        arn:aws:iam::522216370305:role/service-role/recieveFromSlack-role-wel6nx58
      Runtime: nodejs12.x
      Timeout: 3
